import { Router } from "express";
import { makeGroqRequest } from "../lib/groq-keys";
import { AI_MAX_INPUT_CHARS } from "../middlewares/ai-protection";

const router = Router();

const DETECT_MODEL = "llama-3.3-70b-versatile";
const HUMANIZE_MODEL = "llama-3.3-70b-versatile";
const MAX_TOKENS = 500;

async function callGroq(
  model: string,
  messages: Array<{ role: string; content: string }>,
  res: import("express").Response,
): Promise<string | null> {
  let apiRes: Response;
  try {
    apiRes = await makeGroqRequest({
      model,
      max_tokens: MAX_TOKENS,
      temperature: 0.1,
      messages,
    });
  } catch {
    res.status(429).json({ error: "Rate limit reached. Please wait and try again." });
    return null;
  }

  if (!apiRes.ok) {
    res.status(apiRes.status === 429 ? 429 : 500).json({
      error: apiRes.status === 429
        ? "Rate limit reached. Please wait and try again."
        : "AI service temporarily unavailable.",
    });
    return null;
  }

  let data: { choices?: Array<{ message?: { content?: string } }> };
  try {
    data = (await apiRes.json()) as typeof data;
  } catch {
    res.status(500).json({ error: "AI service temporarily unavailable." });
    return null;
  }
  return data.choices?.[0]?.message?.content ?? "";
}

router.post("/ai-detector/detect", async (req, res) => {
  try {
    const { text } = req.body as { text?: string };

    if (!text || text.trim().length < 30) {
      res.status(400).json({ error: "Please provide at least 30 characters of text." });
      return;
    }
    if (text.length > AI_MAX_INPUT_CHARS) {
      res.status(400).json({ error: `Text too long. Maximum ${AI_MAX_INPUT_CHARS} characters.` });
      return;
    }

    const DETECT_CHAR_LIMIT = 3000;
    const analysisText = text.trim().slice(0, DETECT_CHAR_LIMIT);

    const prompt = `You are an expert AI text detection system. Analyze the following text and determine the probability that it was generated by an AI.

TEXT TO ANALYZE:
"""
${analysisText}
"""

Analyze for AI writing signals: uniform sentence rhythm, overuse of transitional phrases, passive voice, hedging language, lack of personal voice, perfect grammar.

Return ONLY valid JSON (no markdown), exactly:
{
  "score": <integer 0-100, where 100 = definitely AI>,
  "label": "<one of: 'Likely Human', 'Possibly Human', 'Mixed / Uncertain', 'Possibly AI', 'Likely AI-Generated'>",
  "confidence": "<one of: 'low', 'medium', 'high'>",
  "summary": "<2-3 sentence plain-English explanation>",
  "indicators": ["<up to 5 specific signals found>"]
}`;

    const raw = await callGroq(DETECT_MODEL, [{ role: "user", content: prompt }], res);
    if (raw === null) return;

    let parsed: unknown;
    try {
      const jsonMatch = raw.match(/\{[\s\S]*\}/);
      parsed = JSON.parse(jsonMatch?.[0] ?? raw);
    } catch {
      res.status(500).json({ error: "Failed to parse detection result. Please try again." });
      return;
    }
    res.json(parsed);
  } catch (err) {
    req.log?.error({ err }, "ai-detector detect error");
    res.status(500).json({ error: "AI service temporarily unavailable." });
  }
});

router.post("/ai-detector/humanize", async (req, res) => {
  try {
    const { text, style } = req.body as { text?: string; style?: string };

    if (!text || text.trim().length < 30) {
      res.status(400).json({ error: "Please provide at least 30 characters of text." });
      return;
    }
    if (text.length > AI_MAX_INPUT_CHARS) {
      res.status(400).json({ error: `Text too long. Maximum ${AI_MAX_INPUT_CHARS} characters.` });
      return;
    }

    const styleGuide: Record<string, string> = {
      casual:       "casual and conversational — short sentences, contractions, relatable",
      professional: "professional but warm — clear, direct, no jargon",
      academic:     "academic but readable — precise and structured with a real voice",
      creative:     "creative and expressive — vivid, personal, varied rhythm",
    };
    const tone = styleGuide[style ?? "casual"] ?? styleGuide["casual"]!;

    const prompt = `Rewrite the following AI-generated text to sound human. Style: ${tone}.
Rules: use contractions, vary sentence length, remove AI filler phrases, use active voice, keep all facts.
Output ONLY the rewritten text.

ORIGINAL:
"""
${text.trim()}
"""`;

    const result = await callGroq(HUMANIZE_MODEL, [{ role: "user", content: prompt }], res);
    if (result === null) return;
    res.json({ humanized: result.trim() });
  } catch (err) {
    req.log?.error({ err }, "ai-detector humanize error");
    res.status(500).json({ error: "AI service temporarily unavailable." });
  }
});

export default router;
