// Requires GROQ_API_KEY in Vercel environment variables
import { Router } from "express";
import { fetchWithGroqKeyRotation, hasGroqKeys } from "../lib/groq-keys";
import { AI_MAX_INPUT_CHARS } from "../middlewares/ai-protection";

const router = Router();

const GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";
const DETECT_MODEL = "llama-3.3-70b-versatile";
const HUMANIZE_MODEL = "llama-3.3-70b-versatile";
const MAX_TOKENS = 500;

// FIXED: AI Detector - callGroq wrapped in try/catch, returns null on any failure
async function callGroq(
  model: string,
  prompt: string,
  res: import("express").Response,
): Promise<string | null> {
  if (!hasGroqKeys()) {
    res.status(500).json({ error: "AI service is temporarily unavailable." });
    return null;
  }

  const { res: apiRes, exhausted } = await fetchWithGroqKeyRotation((key) =>
    fetch(GROQ_URL, {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        max_tokens: MAX_TOKENS,
        temperature: 0.1,
        messages: [{ role: "user", content: prompt }],
      }),
      signal: AbortSignal.timeout(30000),
    }),
  );

  if (exhausted || !apiRes.ok) {
    if (apiRes.status === 429) {
      res.status(429).json({ error: "Service is rate-limited. Please try again in a moment." });
      return null;
    }
    const e = (await apiRes.json().catch(() => ({}))) as { error?: { message?: string } };
    res.status(500).json({ error: e?.error?.message ?? "AI service is temporarily unavailable." });
    return null;
  }

  let data: { choices?: Array<{ message?: { content?: string } }> };
  try {
    data = (await apiRes.json()) as typeof data;
  } catch {
    res.status(500).json({ error: "AI service is temporarily unavailable." });
    return null;
  }
  return data.choices?.[0]?.message?.content ?? "";
}

// FIXED: AI Detector detect route - wrapped in try/catch
router.post("/ai-detector/detect", async (req, res) => {
  try {
    const { text } = req.body as { text?: string };

    if (!text || text.trim().length < 30) {
      res.status(400).json({ error: "Please provide at least 30 characters of text." });
      return;
    }
    if (text.length > AI_MAX_INPUT_CHARS) {
      res.status(400).json({ error: `Text too long. Maximum ${AI_MAX_INPUT_CHARS} characters.` });
      return;
    }

    const prompt = `You are an expert AI text detection system. Analyze the following text and determine the probability that it was generated by an AI.

TEXT TO ANALYZE:
"""
${text.trim()}
"""

Analyze for AI writing signals: uniform sentence rhythm, overuse of transitional phrases, passive voice, hedging language, lack of personal voice, perfect grammar.

Return ONLY valid JSON (no markdown), exactly:
{
  "score": <integer 0-100, where 100 = definitely AI>,
  "label": "<one of: 'Likely Human', 'Possibly Human', 'Mixed / Uncertain', 'Possibly AI', 'Likely AI-Generated'>",
  "confidence": "<one of: 'low', 'medium', 'high'>",
  "summary": "<2-3 sentence plain-English explanation>",
  "indicators": ["<up to 5 specific signals found>"]
}`;

    const raw = await callGroq(DETECT_MODEL, prompt, res);
    if (raw === null) return;

    let parsed: unknown;
    try {
      const jsonMatch = raw.match(/\{[\s\S]*\}/);
      parsed = JSON.parse(jsonMatch?.[0] ?? raw);
    } catch {
      res.status(500).json({ error: "Failed to parse detection result. Please try again." });
      return;
    }
    res.json(parsed);
  } catch (err) {
    req.log?.error({ err }, "ai-detector detect error");
    res.status(500).json({ error: "AI service is temporarily unavailable." });
  }
});

// FIXED: AI Detector humanize route - wrapped in try/catch
router.post("/ai-detector/humanize", async (req, res) => {
  try {
    const { text, style } = req.body as { text?: string; style?: string };

    if (!text || text.trim().length < 30) {
      res.status(400).json({ error: "Please provide at least 30 characters of text." });
      return;
    }
    if (text.length > AI_MAX_INPUT_CHARS) {
      res.status(400).json({ error: `Text too long. Maximum ${AI_MAX_INPUT_CHARS} characters.` });
      return;
    }

    const styleGuide: Record<string, string> = {
      casual:       "casual and conversational — short sentences, contractions, relatable",
      professional: "professional but warm — clear, direct, no jargon",
      academic:     "academic but readable — precise and structured with a real voice",
      creative:     "creative and expressive — vivid, personal, varied rhythm",
    };
    const tone = styleGuide[style ?? "casual"] ?? styleGuide["casual"]!;

    const prompt = `Rewrite the following AI-generated text to sound human. Style: ${tone}.
Rules: use contractions, vary sentence length, remove AI filler phrases, use active voice, keep all facts.
Output ONLY the rewritten text.

ORIGINAL:
"""
${text.trim()}
"""`;

    const result = await callGroq(HUMANIZE_MODEL, prompt, res);
    if (result === null) return;
    res.json({ humanized: result.trim() });
  } catch (err) {
    req.log?.error({ err }, "ai-detector humanize error");
    res.status(500).json({ error: "AI service is temporarily unavailable." });
  }
});

export default router;
