// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-redesign/Glass.tsx": () => import("../components/mockups/hero-redesign/Glass.tsx"),
  "./components/mockups/hero-redesign/Gradient.tsx": () => import("../components/mockups/hero-redesign/Gradient.tsx"),
  "./components/mockups/hero-redesign/Light.tsx": () => import("../components/mockups/hero-redesign/Light.tsx"),
  "./components/mockups/nav-redesign/VariantA.tsx": () => import("../components/mockups/nav-redesign/VariantA.tsx"),
  "./components/mockups/nav-redesign/VariantB.tsx": () => import("../components/mockups/nav-redesign/VariantB.tsx"),
  "./components/mockups/navbar-redesign/Dark.tsx": () => import("../components/mockups/navbar-redesign/Dark.tsx"),
  "./components/mockups/navbar-redesign/Floating.tsx": () => import("../components/mockups/navbar-redesign/Floating.tsx"),
  "./components/mockups/navbar-redesign/GlassNav.tsx": () => import("../components/mockups/navbar-redesign/GlassNav.tsx"),
  "./components/mockups/navbar-redesign/Light.tsx": () => import("../components/mockups/navbar-redesign/Light.tsx"),
  "./components/mockups/navbar-redesign/Minimal.tsx": () => import("../components/mockups/navbar-redesign/Minimal.tsx"),
  "./components/mockups/replit-theme/HomePage.tsx": () => import("../components/mockups/replit-theme/HomePage.tsx"),
  "./components/mockups/xtoolkit/Homepage.tsx": () => import("../components/mockups/xtoolkit/Homepage.tsx"),
  "./components/mockups/xtoolkit/Navbar.tsx": () => import("../components/mockups/xtoolkit/Navbar.tsx")
};
