// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-redesign/Glass.tsx": () => import("../components/mockups/hero-redesign/Glass.tsx"),
  "./components/mockups/hero-redesign/Gradient.tsx": () => import("../components/mockups/hero-redesign/Gradient.tsx"),
  "./components/mockups/hero-redesign/Light.tsx": () => import("../components/mockups/hero-redesign/Light.tsx")
};
